[project]
name = "tsdb-alchemy"
version = "0.1.0"
description = "SQLAlchemy dialect for TSDB Distributed Query Engine via ADBC"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "Apache-2.0" }
authors = [
  { name = "Maciej Kurczewski" }
]
dependencies = [
  "adbc-driver-flightsql>=0.10.0",
  "sqlalchemy<2.0",
  "pyarrow>=18.1.0",
]

[project.entry-points."sqlalchemy.dialects"]
tsdb = "tsdb_alchemy.dialect:TSDBDialect"

[project.entry-points."superset.db_engine_specs"]
tsdb = "tsdb_alchemy.superset.db_engine:DqeEngineSpec"

[build-system]
requires = ["hatchling>=1.18"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pytest>=8.4.2",
    "sqlalchemy[mypy]<2.0",
]
